apiVersion: v1
kind: Service
metadata:
  name: chat-app-service
  namespace: mominur
spec:
  selector:
    app: chat-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
